// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReviews.Data.Context;

#nullable disable

namespace RestaurantReviews.Data.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20230523000319_add-data")]
    partial class adddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurantReviews.Models.Cuisine", b =>
                {
                    b.Property<string>("CuisineCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CssClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuisineCode");

                    b.ToTable("Cuisines");

                    b.HasData(
                        new
                        {
                            CuisineCode = "Chinese",
                            Description = "Chinese",
                            DisplayName = "Chinese"
                        },
                        new
                        {
                            CuisineCode = "Pizza",
                            Description = "Pizza",
                            DisplayName = "Pizza"
                        },
                        new
                        {
                            CuisineCode = "Healthy",
                            Description = "Healthy",
                            DisplayName = "Healthy"
                        },
                        new
                        {
                            CuisineCode = "Mexican",
                            Description = "Mexican",
                            DisplayName = "Mexican"
                        },
                        new
                        {
                            CuisineCode = "Indian",
                            Description = "Indian Food",
                            DisplayName = "Indian"
                        },
                        new
                        {
                            CuisineCode = "Italian",
                            Description = "Italian Food",
                            DisplayName = "Italian"
                        },
                        new
                        {
                            CuisineCode = "French",
                            Description = "French",
                            DisplayName = "French"
                        },
                        new
                        {
                            CuisineCode = "Russian",
                            Description = "Russian",
                            DisplayName = "Russian"
                        },
                        new
                        {
                            CuisineCode = "American",
                            Description = "American",
                            DisplayName = "American"
                        },
                        new
                        {
                            CuisineCode = "Ukrainian",
                            Description = "Ukrainian",
                            DisplayName = "Ukrainian"
                        });
                });

            modelBuilder.Entity("RestaurantReviews.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuisineCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceRange")
                        .HasColumnType("int");

                    b.Property<string>("StateCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.HasIndex("CuisineCode");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("RestaurantReviews.Models.RestaurantReview", b =>
                {
                    b.Property<int>("RestaurantReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantReviewId"), 1L, 1);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantReviewId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantReviews");
                });

            modelBuilder.Entity("RestaurantReviews.Models.Restaurant", b =>
                {
                    b.HasOne("RestaurantReviews.Models.Cuisine", "Cuisine")
                        .WithMany("Restaurants")
                        .HasForeignKey("CuisineCode")
                        .HasConstraintName("FK_Restaurants_Cuisines");

                    b.Navigation("Cuisine");
                });

            modelBuilder.Entity("RestaurantReviews.Models.RestaurantReview", b =>
                {
                    b.HasOne("RestaurantReviews.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReviews.Models.Cuisine", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("RestaurantReviews.Models.Restaurant", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
